### PR TITLE
twitter_delete: allow inline env setting

### PR DESCRIPTION
**Pull request by DomT4**
Patch proposal:

* Allows inline ENV setting for the variables if they aren't detected in the `env`. This shells out, but I guess it's not completely awful in this context.

* Makes unfavouriting tweets require an option, instead of being the default. This one may be subjective - I feel a little stronger towards the content that I've favourited rather than the inane babble I tweet most of the time.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@DomT4 Sorry for the delay, turns out I wasn't watching this repo. I'm :+1: on the favouriting change but :-1: on the `ENV` one. Happy to merge if you can tweak that. Thanks!

**Comment by mikemcquaid** [comment]
Passing on this PR until conflicts resolved etc. :wink:

**Comment by DomT4** [comment]
I may never recover from the shame of having one of my PRs closed due to inactivity ;). Will take another look at these soon!

**Comment by mikemcquaid** [comment]
Haha, no worries!

**Pull request closed without merging**
